### ISSUE TITLE
text to speech doesnot work in local environment

### ISSUE THREAD

**Issue by himars3290** [googleapis/nodejs-text-to-speech#266] opened 2019-09-11 16:04 UTC
#### Environment details

  - OS: Linux/Ubuntu
  - Node.js version: v10.14.1
  - npm version:
  - `@google-cloud/text-to-speech` version: 1.2.0

#### Steps to reproduce

  1. run sample quickstart.js on local machine
  2. command used: node quickstart.js

ERROR stack trace
```
TypeError: Cannot read property 'length' of undefined
    at Root.load (../node_modules/protobufjs/src/root.js:192:44)
    at Root.loadSync (../node_modules/protobufjs/src/root.js:235:17)
    at Object.loadSync (../node_modules/@grpc/proto-loader/build/src/index.js:230:27)
    at GrpcClient.loadFromProto (../node_modules/google-gax/build/src/grpc.js:118:44)
    at GrpcClient.loadProto (../node_modules/google-gax/build/src/grpc.js:145:21)
    at new TextToSpeechClient (../node_modules/@google-cloud/text-to-speech/src/v1/text_to_speech_client.js:120:28)
    at main (../quickstart.js:27:20)
    at Object.<anonymous> (../quickstart.js:49:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)

Line corresponding to error at line 27
`const client = new textToSpeech.TextToSpeechClient();`

but the same code works in google cloud shell

**Comment by callmehiphop** [comment] 2019-09-11 16:56
Appears to be a duplicate of https://github.com/googleapis/nodejs-scheduler/issues/131. @alexander-fenster any thoughts here? I've been unable to reproduce so far, but it looks like something is going wrong when trying to load the JSON files.

**Comment by alexander-fenster** [comment] 2019-09-11 20:33
@himars3290 Just to rule out some special stuff - can you please confirm it has nothing to do with Electron and other frameworks, but fails in a regular Node.js shell? E.g. if you just do this in your Linux/Ubuntu terminal:

```
$ mkdir test-install
$ cd test-install
$ echo {} > package.json
$ npm install @google-cloud/text-to-speech
$ node
> const tts = require('@google-cloud/text-to-speech');
undefined
> const client = new tts.TextToSpeechClient();
undefined   <<< no exception means it worked
> client
TextToSpeechClient {
  _descriptors: {},
  auth: GoogleAuth {
    checkIsGCE: false,
    jsonContent: null,
    cachedCredential: null,
    _cachedProjectId: null,
    keyFilename: undefined,
    scopes: [ 'https://www.googleapis.com/auth/cloud-platform' ],
    clientOptions: undefined
  },
  _innerApiCalls: { listVoices: [Function], synthesizeSpeech: [Function] }
}
```

Does it work as ^^^ above? If not, can you please paste the whole session log here?

Thank you for helping us debug the problem!

**Comment by alexander-fenster** [comment] 2019-09-13 16:57
@himars3290 Which version of `google-gax` is downloaded in your `node_modules`? Can you please run `npm ls` and paste the output?

If `google-gax` is older than `1.5.2` then please do `rm -rf node_modules package-lock.json`, reinstall and make sure it's recent.

Thank you!

**Comment by alexander-fenster** [comment] 2019-09-16 19:30
@himars3290 We got a confirmation from other users that this problem is indeed caused by stale dependency `google-gax`. Please feel free to reopen the issue if reinstalling all dependencies (without `package-lock.json`) does not help fix this issue for you.

**Closed by alexander-fenster** 2019-09-16 19:30 UTC
Labels: priority: p2, status: duplicate, type: bug
